# Generated by Django 2.0.6 on 2018-12-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='示例企业', max_length=200, null=True)),
                ('owner', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('总经理', '总经理'), ('厂长', '厂长'), ('生产主管', '生产主管'), ('仓管', '仓管'), ('空', '空')], default='空', max_length=200, null=True)),
                ('realname', models.CharField(default='空', max_length=256, null=True)),
                ('company', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membs', to='account.Company')),
            ],
        ),
        migrations.CreateModel(
            name='WeixinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=256, null=True)),
                ('nickname', models.CharField(max_length=256, null=True)),
                ('sex', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.WeixinUser'),
        ),
    ]
