# Generated by Django 2.0.6 on 2018-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181015_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('A', '总经理'), ('B', '厂长'), ('C', '生产主管'), ('D', '仓管')], max_length=200, null=True),
        ),
    ]
