# Generated by Django 2.0.6 on 2018-12-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20181218_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=512)),
                ('expires', models.IntegerField(blank=True)),
            ],
        ),
    ]
