# Generated by Django 2.0.6 on 2018-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181016_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default='空', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dept',
            field=models.CharField(choices=[('总经理', '总经理'), ('厂长', '厂长'), ('生产主管', '生产主管'), ('仓管', '仓管'), ('空', '空')], default='空', max_length=200, null=True),
        ),
    ]
