# Generated by Django 2.0.6 on 2018-11-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181025_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=256, null=True)),
                ('nickname', models.CharField(max_length=256, null=True)),
                ('sex', models.CharField(max_length=256, null=True)),
                ('city', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.WeixinUser'),
        ),
    ]
