# Generated by Django 2.0.6 on 2018-11-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20181102_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(default='空', max_length=256, null=True),
        ),
    ]
