# Generated by Django 2.0.6 on 2018-11-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_real_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='real_name',
            new_name='realname',
        ),
    ]
