# Generated by Django 2.0.6 on 2018-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_cd', models.CharField(max_length=10)),
                ('stat_nam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orders_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200, null=True)),
                ('order_time', models.DateField()),
                ('sub_time', models.DateField()),
                ('order_num', models.CharField(max_length=200, null=True)),
                ('order_detail', models.CharField(max_length=200, null=True)),
                ('ps', models.CharField(max_length=200)),
                ('order_status', models.CharField(max_length=10)),
                ('person_incharge', models.CharField(max_length=100)),
            ],
        ),
    ]
