# Generated by Django 2.0.6 on 2018-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_list',
            name='order_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='sub_time',
            field=models.CharField(max_length=200),
        ),
    ]
