# Generated by Django 2.0.6 on 2019-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_list',
            name='order_quantity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
