# Generated by Django 2.0.6 on 2019-02-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0002_auto_20190218_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_list',
            name='remark',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='requirement',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
