# Generated by Django 2.0.6 on 2018-08-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0002_auto_20180825_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_list',
            name='order_status',
            field=models.IntegerField(max_length=10),
        ),
    ]
