# Generated by Django 2.0.6 on 2019-02-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0003_auto_20190220_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_list',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='requirement',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
