# Generated by Django 2.0.6 on 2018-08-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0003_auto_20180825_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_stat',
            name='stat_cd',
            field=models.IntegerField(max_length=10),
        ),
    ]
