# Generated by Django 2.0.6 on 2018-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0004_auto_20180825_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_stat',
            name='id',
        ),
        migrations.AddField(
            model_name='orders_list',
            name='uuid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order_stat',
            name='stat_cd',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='order_status',
            field=models.IntegerField(),
        ),
    ]
