# Generated by Django 2.0.6 on 2018-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0005_auto_20180825_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='charge_person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_cd', models.CharField(max_length=200)),
                ('person_nam', models.CharField(max_length=200)),
            ],
        ),
    ]
