# Generated by Django 2.0.6 on 2018-10-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0006_charge_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_list',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='order_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders_list',
            name='sub_time',
            field=models.DateField(),
        ),
    ]
