# Generated by Django 2.0.6 on 2018-11-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0007_auto_20181009_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_list',
            name='openid',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
