# Generated by Django 2.0.6 on 2018-11-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0009_auto_20181107_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_list',
            old_name='order_qunantity',
            new_name='order_quantity',
        ),
    ]
