# Generated by Django 2.0.6 on 2018-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_flow', '0010_auto_20181107_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_list',
            name='company',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
